# Generated by Django 4.1.2 on 2022-11-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cities",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("city", models.CharField(max_length=200)),
                ("state_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=25, null=True)),
                ("score_date", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClinicalTool",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("patient_name", models.CharField(max_length=25, null=True)),
                ("score_date", models.DateField(null=True)),
                (
                    "age",
                    models.IntegerField(
                        choices=[
                            (1, "<65(0 Score)"),
                            (2, "65-74(+1 Score)"),
                            (3, ">=75(+2 Score"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HCPConnect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Blog_title", models.CharField(max_length=255, null=True)),
                ("Blog_author", models.CharField(max_length=255, null=True)),
                ("Blog_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("Blog_description", models.TextField()),
                ("Blog_image", models.ImageField(upload_to="image")),
            ],
        ),
        migrations.CreateModel(
            name="Livewebinar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("webinar_title", models.CharField(max_length=255, null=True)),
                ("webinar_link", models.CharField(max_length=255, null=True)),
                ("webinar_date", models.DateTimeField()),
                ("webniar_image", models.ImageField(upload_to="image")),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_type", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=70, unique=True)),
                ("mobile", models.CharField(max_length=15)),
                ("state", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WebinarList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("webinar_title", models.CharField(max_length=255, null=True)),
                ("webinar_link", models.CharField(max_length=255, null=True)),
                ("webinar_date", models.DateTimeField()),
                ("webniar_image", models.ImageField(upload_to="image")),
            ],
        ),
    ]
